### ISSUE TITLE
Parameter order

### ISSUE THREAD

**Issue by martinbohmcz** [Pixidos/GPWebPay#18]
Hello.

Thanks for updating this for Nette 3.0. I have tried it and all worked until I have tried to communicate with the test environment. It has been constantly returning PRCODE=31 (Wrong digest). I have checked that with the support and they have suggested to have the parameters (MERCHANTID, OPERATION etc.) in the same order as they are in documentation, which finally helped.

Anybody else experienced this?

I have thought that the possible solution might be to switch order of parameters in **DigestParams.php** line 60

change this:
return array_intersect_key($params, array_flip(self::DIGEST_PARAMS_KEYS));

to this:
return array_intersect_key(array_flip(self::DIGEST_PARAMS_KEYS), $params);

but that would overwrite the values of my parameters with the default ones.

**Comment by ondraondra81** [comment]
I try resolve this issue tomorrow. But can you send me contact on you. Probably I need help with testing environment.  My email you can find in some php file :)

**Comment by ondraondra81** [comment]
Ready for testing ;)

**Comment by martinbohmcz** [comment]
Tested. :) Everything works as intended. Thank you.
