### ISSUE TITLE
Update the latte/latte dependency

### ISSUE THREAD

**Issue by jaroslavlibal** [Pixidos/GPWebPay#25]
Would it be possible to update (enable 3.x version) of latte/latte dependencies, please?

If I looked correctly, it's required just for the [gpWebPayControl.latte](https://github.com/Pixidos/GPWebPay/blob/master/src/Components/templates/gpWebPayControl.latte) template, where it shouldn't be a problem to add support for the latest latte.

Thanks!

**Comment by ondraondra81** [comment]
Yes, I will in a few days.

**Comment by martinbohmcz** [comment]
And it would be nice if you can raise the supported PHP version to 8.1 as well. Thank you.

**Comment by ondraondra81** [comment]
done in version 3.4
